baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'Rodrigue BOUREL'
theme = 'gallery'
enableRobotsTXT = true

[params]
  defaultTheme = "dark"

[module]
  [[module.imports]]
    path = "github.com/nicokaiser/hugo-theme-gallery/v4"